class Fighter{
  constructor(x,y,style){this.x=x;this.y=y;this.z=0;this.vx=0;this.vy=0;this.vz=0;this.face=1;this.style=style;this.radius=24;this.state='idle';this.stateFrame=0;this.stun=0;this.inv=0;this.flash=0;this.dead=false;this.knockdown=0;this.attackCooldown=0;this.alpha=1;this.scale=1}
  getStyle(){return STYLES[this.style]||STYLES.anbu}
  updateMotion(){
    this.x+=this.vx;this.y+=this.vy;this.vx*=.82;this.vy*=.82;
    if(this.z>0||this.vz>0){this.z+=this.vz;this.vz-=.72;if(this.z<=0){this.z=0;this.vz=0;if(this.state==='jump')this.state='idle'}}
    if(this.inv>0)this.inv--;if(this.flash>0)this.flash--;if(this.stun>0)this.stun--;if(this.attackCooldown>0)this.attackCooldown--;
  }
  burst(color,count=10,power=1){for(let i=0;i<count;i++)Game.particles.push(new Particle(this.x,this.y,this.z+45,color,power))}
  draw(cameraX){drawFighter(this,cameraX)}
}

class Player extends Fighter{
  constructor(charId,x,y){
    const def=CHARACTERS[charId];super(x,y,def.forms[0].style);this.charId=charId;this.def=def;this.formIndex=0;this.form=def.forms[0];this.maxHp=this.form.hp;this.hp=this.maxHp;this.energy=this.form.energyMax;this.evolve=0;this.combo=0;this.comboTimer=0;this.lightStep=0;this.attack=null;this.queuedLight=false;this.queuedHeavy=false;this.lastMove=0;this.kills=0;this.damageTaken=0;this.score=0;this.dashing=0;this.specialAura=0;this.style=this.form.style;this.radius=25;
  }
  difficultyMul(){return save.settings.difficulty==='easy'?.85:save.settings.difficulty==='hard'?1.15:1}
  input(action){if(this.dead||Game.state!=='playing')return;if(action==='light')this.lightAttack();if(action==='heavy')this.heavyAttack();if(action==='special')this.specialAttack();if(action==='dash')this.dash();if(action==='jump')this.jump();if(action==='evolve')this.doEvolve()}
  jump(){if(this.z===0&&this.stun===0&&!this.attack&&this.dashing===0){this.vz=11.2;this.state='jump';audio.sfx('dash')}}
  dash(){if(this.stun||this.dashing||this.attack||this.energy<10)return;this.energy-=10;this.dashing=16;this.inv=18;this.state='dash';this.vx=this.face*11.5;audio.sfx('dash');vibrate(8)}
  lightAttack(){if(this.stun||this.knockdown)return;if(this.z>8){if(!this.attack)this.startAttack('air',0);return}if(this.dashing>5){this.startAttack('dash',0);this.dashing=0;return}if(this.attack){if(this.attack.kind==='light'&&this.attack.frame>=5)this.queuedLight=true;return}this.startAttack('light',this.comboTimer>0?this.lightStep:0)}
  heavyAttack(){if(this.stun||this.knockdown)return;const grab=Game.enemies.find(e=>!e.dead&&e.stun>0&&Math.abs(e.x-this.x)<52&&Math.abs(e.y-this.y)<34);if(grab&&!this.attack&&this.z===0){this.startAttack('throw',0,grab);return}if(this.attack&&this.attack.kind==='light'&&this.attack.step<2&&this.attack.frame>6){this.queuedHeavy=true;return}if(!this.attack&&this.z===0)this.startAttack('heavy',0)}
  specialAttack(){if(this.stun||this.knockdown||this.attack||this.dashing)return;const cost=this.form.name==='Bafolight'||this.form.name==='Bafolantern'?28:34;if(this.energy<cost){Game.texts.push(new FloatText(this.x,this.y,110,'ÉNERGIE !','#82e8c4',13));return}this.energy-=cost;this.startAttack('special',0);audio.sfx('special');vibrate([10,12,10])}
  startAttack(kind,step=0,target=null){const configs={light:{duration:18,hit:7,step},heavy:{duration:30,hit:14,step},special:{duration:42,hit:17,step},dash:{duration:22,hit:7,step},air:{duration:25,hit:9,step},throw:{duration:34,hit:17,step,target}};this.attack={kind,frame:0,...configs[kind],hitDone:false,target};this.state=kind==='special'?'special':'attack';this.queuedLight=false;this.queuedHeavy=false}
  resolveAttack(a){
    const p=this.form.power;let dmg=10,range=74,knock=4,special=false,down=false;
    if(a.kind==='light'){const ds=[10,12,14,22];dmg=ds[a.step%4]*p;range=72+(a.step===3?10:0);knock=a.step===3?8:3.8;down=a.step===3}
    if(a.kind==='heavy'){dmg=31*p;range=88;knock=9;down=true;audio.sfx('heavy')}
    if(a.kind==='dash'){dmg=24*p;range=96;knock=8;down=true}
    if(a.kind==='air'){dmg=27*p;range=78;knock=7;down=true}
    if(a.kind==='throw'){const t=a.target;if(t&&!t.dead&&Math.abs(t.x-this.x)<80){t.takeHit(38*p,this.face,{knockback:12,knockdown:true});t.vy=rand(-2,2);this.addScore(120);audio.sfx('heavy');vibrate(18)}return}
    if(a.kind==='special'){
      special=true;
      if(this.charId==='zaim'){dmg=(this.formIndex===2?55:38)*p;range=this.formIndex===2?150:110;knock=10;down=true;Game.projectiles.push(new Projectile('player',this.x+this.face*45,this.y,this.z+48,this.face*(this.formIndex===2?8.5:7),0,{damage:Math.round(dmg*.62),r:this.formIndex===2?34:26,color:'#63f7cf',kind:'spiral',pierce:this.formIndex===2}))}
      else if(this.charId==='emerald'){dmg=32*p;range=150;knock=8;down=true;for(const off of [-22,0,22])Game.projectiles.push(new Projectile('player',this.x+this.face*40,this.y+off,this.z+42,this.face*6.5,off*.025,{damage:Math.round(dmg*.7),r:22,color:'#4dffad',kind:'ball',pierce:this.formIndex>0}))}
      else{dmg=42*p;range=128;knock=11;down=true;this.vx=this.face*8}
    }
    let hits=0;for(const e of Game.enemies){if(e.dead||e.inv>0)continue;const dx=(e.x-this.x)*this.face;if(dx>-25&&dx<range&&Math.abs(e.y-this.y)<46&&Math.abs(e.z-this.z)<70){hits++;e.takeHit(Math.round(dmg),this.face,{knockback:knock,knockdown:down,special});if(a.kind==='light'&&a.step===2){e.vz=5.5;e.z=1}this.addHit(e,Math.round(dmg),special)}}
    this.hitObjects(range,Math.round(dmg));if(hits){audio.sfx(a.kind==='heavy'?'heavy':'hit');Game.freeze=a.kind==='special'?4:a.kind==='heavy'?3:2;Game.shake=Math.max(Game.shake,a.kind==='special'?9:a.kind==='heavy'?7:4);vibrate(a.kind==='special'?16:7)}
  }
  hitObjects(range,dmg){for(const o of Game.objects){if(o.dead)continue;const dx=(o.x-this.x)*this.face;if(dx>-20&&dx<range&&Math.abs(o.y-this.y)<52){o.hp-=dmg;o.flash=6;if(o.hp<=0)o.break()}}}
  addHit(enemy,dmg,special){this.combo++;this.comboTimer=105;this.evolve=clamp(this.evolve+(special?6:3.5),0,100);this.addScore(Math.round((10+dmg*.45)*Math.min(8,1+this.combo*.12)));Game.texts.push(new FloatText(enemy.x,enemy.y,enemy.z+100,`-${dmg}`,special?'#75ffd5':'#fff',special?19:15))}
  addScore(n){this.score+=n;Game.score=this.score}
  doEvolve(){if(this.evolve<100||this.formIndex>=this.def.forms.length-1||this.attack||this.stun)return;this.formIndex++;const oldMax=this.maxHp,oldRatio=this.hp/oldMax;this.form=this.def.forms[this.formIndex];this.style=this.form.style;this.maxHp=this.form.hp;this.hp=Math.max(this.hp+30,Math.round(this.maxHp*Math.max(.56,oldRatio)));this.hp=Math.min(this.maxHp,this.hp);this.energy=this.form.energyMax;this.evolve=0;this.inv=90;this.specialAura=120;this.burst(this.getStyle().aura||'#7fffd6',45,1.7);audio.sfx('evolve');vibrate([25,25,45]);Game.banner(this.form.name,'ÉVOLUTION PLAYER')}
  takeHit(dmg,dir,opts={}){if(this.inv>0||this.dead)return;const mul=this.difficultyMul();dmg=Math.max(1,Math.round(dmg*mul));this.hp-=dmg;this.damageTaken+=dmg;this.stun=opts.knockdown?30:14;this.vx=dir*(opts.knockback||4);this.flash=8;this.combo=0;this.comboTimer=0;this.attack=null;this.burst('#ff6e82',13,1);Game.texts.push(new FloatText(this.x,this.y,this.z+110,`-${dmg}`,'#ff8da0',17));Game.shake=Math.max(Game.shake,5);audio.sfx('hit');vibrate(10);if(opts.knockdown)this.knockdown=26;if(this.hp<=0){this.hp=0;this.dead=true;this.state='ko';audio.sfx('ko');setTimeout(()=>Game.finish(false),650)}}
  update(){
    this.updateMotion();if(this.dead)return;if(this.specialAura>0)this.specialAura--;if(this.knockdown>0){this.knockdown--;if(this.knockdown===0){this.inv=35;this.stun=0}}if(this.dashing>0){this.dashing--;this.inv=Math.max(this.inv,2);this.vx=this.face*10.5;if(this.dashing===0)this.state='idle'}if(this.comboTimer>0){this.comboTimer--;if(this.comboTimer===0){this.combo=0;this.lightStep=0}}this.energy=clamp(this.energy+.16+(this.formIndex*.025),0,this.form.energyMax);
    if(this.attack){const a=this.attack;a.frame++;if(a.frame===a.hit&&!a.hitDone){a.hitDone=true;this.resolveAttack(a)}if(a.frame>=a.duration){const kind=a.kind,step=a.step;this.attack=null;this.state=this.z>0?'jump':'idle';if(this.queuedHeavy){this.queuedHeavy=false;this.startAttack('heavy',0)}else if(this.queuedLight&&kind==='light'){this.lightStep=(step+1)%4;this.startAttack('light',this.lightStep)}else if(kind==='light'){this.lightStep=(step+1)%4;this.comboTimer=Math.max(this.comboTimer,28)}}}
    if(this.stun===0&&!this.attack&&!this.dashing&&!this.knockdown){let dx=Game.input.right-Game.input.left,dy=Game.input.down-Game.input.up;const gp=Game.gamepadAxes();if(Math.abs(gp.x)>.2)dx=gp.x;if(Math.abs(gp.y)>.2)dy=gp.y;if(dx||dy){const l=Math.hypot(dx,dy)||1;dx/=l;dy/=l;this.x+=dx*this.form.speed;this.y+=dy*this.form.speed*.72;if(Math.abs(dx)>.15)this.face=Math.sign(dx);this.state=this.z>0?'jump':'walk'}else if(this.z===0)this.state='idle'}
    this.y=clamp(this.y,groundTop+25,groundBottom);const maxX=Game.locked?Game.lockMax:Game.level.length-60;this.x=clamp(this.x,35,maxX)
  }
}

class Enemy extends Fighter{
  constructor(key,x,y,zoneId){const d=ENEMIES[key];super(x,y,d.style);this.key=key;this.def=d;this.name=d.name;this.maxHp=this.hp=d.hp;this.speed=d.speed;this.damage=d.damage;this.type=d.type;this.boss=!!d.boss;this.zoneId=zoneId;this.attackTimer=rand(20,60);this.specialTimer=rand(70,130);this.aiOffset=rand(-38,38);this.radius=this.getStyle().huge?38:this.getStyle().big?31:25;this.scale=this.getStyle().huge?1.28:this.getStyle().big?1.14:1;this.shield=this.type==='shield'?45:0;this.phase=0}
  takeHit(dmg,dir,opts={}){if(this.inv>0||this.dead)return;if(this.type==='shield'&&this.shield>0&&dir===-this.face&&!opts.special){const block=Math.min(dmg*.65,this.shield);this.shield-=block;dmg-=block;Game.texts.push(new FloatText(this.x,this.y,this.z+110,'BLOCK','#94ffd7',12))}if(this.type==='counter'&&Math.random()<.12&&!opts.special){this.inv=12;Game.texts.push(new FloatText(this.x,this.y,this.z+100,'COPIE','#a9e8ff',12));Game.player.takeHit(6,-dir,{knockback:3});return}dmg=Math.max(1,Math.round(dmg));this.hp-=dmg;this.stun=opts.special?16:10;this.vx=dir*(opts.knockback||4);this.flash=7;if(opts.knockdown)this.knockdown=20;this.burst(opts.special?'#6fffd5':'#f2dfbd',opts.special?13:7,opts.special?1:.7);if(this.hp<=0){this.hp=0;this.dead=true;this.state='ko';this.deathTimer=36;Game.player.kills++;Game.player.evolve=clamp(Game.player.evolve+(this.boss?12:this.type==='elite'?18:9),0,100);Game.player.addScore(this.boss?900:this.type==='elite'?240:110);if(!this.boss&&Math.random()<.22)Game.spawnPickup(this.x,this.y,Math.random()<.5?'energy':'health');audio.sfx('ko')}}
  attackPlayer(kind='melee'){if(this.dead||Game.player.dead)return;const p=Game.player;if(kind==='ranged'){const col=this.type==='rangedFear'?'#f4dc44':'#65f6b9';Game.projectiles.push(new Projectile('enemy',this.x+this.face*30,this.y,this.z+45,this.face*4.8,0,{damage:this.damage,r:18,color:col,kind:'ball'}));audio.sfx('special');return}if(Math.abs(p.x-this.x)<88&&Math.abs(p.y-this.y)<42&&p.z<55)p.takeHit(this.damage,this.face,{knockback:this.boss?7:4,knockdown:this.boss&&Math.random()<.25})}
  bossPattern(){const p=Game.player,dx=p.x-this.x,dir=Math.sign(dx)||this.face;this.face=dir;if(this.type==='bossNinja'){if(this.specialTimer<=0){this.specialTimer=rand(80,120);this.inv=12;this.vx=dir*9;for(let i=-1;i<=1;i++)Game.projectiles.push(new Projectile('enemy',this.x,this.y+i*28,42,dir*5.6,0,{damage:12,r:18,color:'#ff315c',kind:'slash'}));Game.banner('Nuage interdit','ROOBKATSUKI')}}else if(this.type==='bossEmerald'){if(this.specialTimer<=0){this.specialTimer=rand(90,135);for(let i=-2;i<=2;i++)Game.projectiles.push(new Projectile('enemy',this.x,this.y+i*32,60,dir*(4.2+Math.abs(i)*.35),0,{damage:14,r:21,color:'#f4d52d',kind:'ball',pierce:false}));Game.banner('Peur cosmique','BAFORALLAX')}}else if(this.type==='bossCaster'){if(this.specialTimer<=0){this.specialTimer=rand(75,110);for(let i=0;i<3;i++){const tx=p.x+rand(-120,120),ty=p.y+rand(-50,50);Game.hazards.push({x:tx,y:ty,t:55,r:46,damage:16,color:'#a448df'})}Game.banner('Malédiction suprême','ZARION')}}else if(this.type==='bossRush'||this.type==='bossKayo'){if(this.specialTimer<=0){this.specialTimer=rand(70,105);this.vx=dir*(this.type==='bossKayo'?12:14);this.inv=10;this.attackTimer=18;setTimeout(()=>this.attackPlayer('melee'),120)}}else if(this.type==='bossTank'){if(this.specialTimer<=0){this.specialTimer=rand(105,145);Game.shake=10;for(let i=-2;i<=2;i++)Game.hazards.push({x:this.x+i*75,y:this.y+rand(-25,25),t:35,r:34,damage:17,color:'#7e9db3'});Game.banner('Impact massif','STONARD')}}}
  update(){this.updateMotion();if(this.dead){this.deathTimer--;this.alpha=clamp(this.deathTimer/30,0,1);return}if(this.knockdown>0){this.knockdown--;return}if(this.stun>0)return;this.attackTimer--;this.specialTimer--;const p=Game.player;if(!p||p.dead)return;const dx=p.x-this.x,dy=p.y-this.y,d=Math.hypot(dx,dy*1.3);this.face=dx>=0?1:-1;if(this.boss)this.bossPattern();const ranged=this.type==='ranged'||this.type==='rangedFear',desired=ranged?190:(this.getStyle().huge?78:63);if(this.attackTimer<=0&&d<desired+24&&(!ranged||d<260)){this.attackTimer=this.boss?rand(38,58):rand(55,85);this.state='attack';this.stateFrame=0;setTimeout(()=>{if(!this.dead)this.attackPlayer(ranged?'ranged':'melee')},ranged?160:115)}else{let move=0;if(d>desired+20)move=1;else if(ranged&&d<130)move=-1;if(move){const l=Math.hypot(dx,dy)||1;this.x+=dx/l*this.speed*move;this.y+=dy/l*this.speed*.62*move;this.state='walk'}else this.state='idle'}this.y=clamp(this.y,groundTop+25,groundBottom);this.x=clamp(this.x,20,Game.level.length+150)}
}

class Breakable{
  constructor(x,y,type='crate'){this.x=x;this.y=y;this.type=type;this.hp=36;this.dead=false;this.flash=0}
  break(){if(this.dead)return;this.dead=true;for(let i=0;i<16;i++)Game.particles.push(new Particle(this.x,this.y,30,this.type==='crate'?'#9a7447':'#58d9a2',1.2));if(Math.random()<.75)Game.spawnPickup(this.x,this.y,Math.random()<.58?'health':'energy');Game.player.addScore(40);audio.sfx('heavy')}
  update(){if(this.flash>0)this.flash--}
  draw(cameraX){if(this.dead)return;const x=this.x-cameraX,y=this.y;ctx.save();if(this.flash)ctx.globalAlpha=.55;ctx.fillStyle='#171d1a';ctx.beginPath();ctx.ellipse(x,y+4,28,8,0,0,Math.PI*2);ctx.fill();if(this.type==='crate'){ctx.fillStyle='#6d4d2d';ctx.strokeStyle='#2d2118';ctx.lineWidth=4;ctx.fillRect(x-24,y-45,48,45);ctx.strokeRect(x-24,y-45,48,45);ctx.beginPath();ctx.moveTo(x-22,y-43);ctx.lineTo(x+22,y-3);ctx.moveTo(x+22,y-43);ctx.lineTo(x-22,y-3);ctx.stroke()}else{ctx.fillStyle='#1f5a45';ctx.fillRect(x-18,y-48,36,48)}ctx.restore()}
}
class Pickup{
  constructor(x,y,type){this.x=x;this.y=y;this.type=type;this.life=900;this.phase=rand(0,6)}
  update(){this.life--;const p=Game.player;if(!p||p.dead)return;if(Math.abs(this.x-p.x)<38&&Math.abs(this.y-p.y)<32){if(this.type==='health'){const heal=Math.min(p.maxHp-p.hp,28);p.hp+=heal;Game.texts.push(new FloatText(p.x,p.y,100,`+${heal} PV`,'#69f7a7',14))}else{p.energy=Math.min(p.form.energyMax,p.energy+36);Game.texts.push(new FloatText(p.x,p.y,100,'+CHAKRA','#6ee6ff',14))}p.addScore(25);audio.sfx('pickup');vibrate(6);this.life=0}}
  draw(cameraX){const x=this.x-cameraX,y=this.y-22-Math.sin(Game.time*.1+this.phase)*4;ctx.save();ctx.shadowBlur=15;ctx.shadowColor=this.type==='health'?'#5ef296':'#5fd9ff';ctx.fillStyle=this.type==='health'?'#1e8d54':'#227e9f';ctx.beginPath();ctx.roundRect(x-12,y-18,24,32,6);ctx.fill();ctx.fillStyle='#fff';ctx.font='900 12px system-ui';ctx.textAlign='center';ctx.fillText(this.type==='health'?'+':'⚡',x,y+3);ctx.restore()}
}
