import { getApps, getApp, initializeApp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js';
import { getAuth } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js';
import { getFirestore, collection, addDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={meal:'Mon repas',session:'Ma séance',progress:'Mes progrès'};
const emoji={meal:'🍽️',session:'🏋️‍♀️',progress:'✨'};
let state={type:null,foods:[],exercises:[],imageData:'',progressCompare:false};
let app=null,auth=null,db=null;
function init(){const cfg=window.LARA_FIREBASE_CONFIG;if(!cfg?.apiKey)return false;app=getApps().find(a=>a?.options?.projectId===cfg.projectId)||getApps()[0]||initializeApp(cfg);auth=getAuth(app);db=getFirestore(app);return true;}
function profile(){try{return JSON.parse(localStorage.getItem('laraUserV4'))||JSON.parse(localStorage.getItem('laraUser'))||{}}catch{return {}}}
function userName(){const p=profile();return p.name||auth?.currentUser?.email?.split('@')[0]||'Participante'}
function history(){try{return JSON.parse(localStorage.getItem('laraHistoryV4'))||[]}catch{return []}}
function foods(){const base=['Poulet','Dinde','Œufs','Saumon','Thon','Cabillaud','Steak haché 5%','Tofu','Skyr','Fromage blanc','Yaourt grec','Riz basmati','Riz complet','Pâtes complètes','Patate douce','Pommes de terre','Quinoa','Flocons d’avoine','Pain complet','Wrap complet','Lentilles','Pois chiches','Haricots rouges','Brocolis','Haricots verts','Courgettes','Carottes','Épinards','Salade','Tomates','Concombre','Avocat','Banane','Pomme','Fruits rouges','Kiwi','Orange','Amandes','Noix','Beurre de cacahuète','Huile d’olive','Chocolat noir','Whey','Smoothie','Bowl','Omelette','Salade composée','Soupe','Porridge'];return [...new Set([...base,...(window.LARA_EXTRA_FOODS||[])])].sort((a,b)=>a.localeCompare(b,'fr'))}
function exercises(){let list=[];try{if(Array.isArray(EXERCISES))list=EXERCISES.map(e=>e.name||e.title).filter(Boolean)}catch{} if(Array.isArray(window.LARA_EXTRA_EXERCISES))list=list.concat(window.LARA_EXTRA_EXERCISES);return [...new Set(list)].sort((a,b)=>a.localeCompare(b,'fr'))}
function ensureModal(){let m=document.getElementById('publishModal');if(!m){m=document.createElement('div');m.id='publishModal';m.className='publishModal';document.body.appendChild(m)}m.innerHTML='<div class="publishOverlay"></div><section class="publishSheet"><div class="publishHandle"></div><header class="publishHeader"><button id="publishBack" class="publishIconBtn">←</button><div><b id="publishTitle">Créer une publication</b><span id="publishSub">Choisis ce que tu veux partager</span></div><button id="publishClose" class="publishIconBtn">×</button></header><div id="publishBody" class="publishBody"></div></section>';m.querySelector('.publishOverlay').onclick=close;m.querySelector('#publishClose').onclick=close;m.querySelector('#publishBack').onclick=choice;return m}
function open(type=null){document.body.classList.remove('composer-open');state={type,foods:[],exercises:[],imageData:'',progressCompare:false};ensureModal().classList.add('open');type?form(type):choice()}
function close(){document.getElementById('publishModal')?.classList.remove('open')}
function title(t,s,back=false){document.getElementById('publishTitle').textContent=t;document.getElementById('publishSub').textContent=s;document.getElementById('publishBack').style.visibility=back?'visible':'hidden'}
function choice(){state.type=null;title('Créer une publication','Choisis ce que tu veux partager');document.getElementById('publishBody').innerHTML='<div class="publishChoiceGrid"><button class="publishChoice meal" data-t="meal"><span>🍽️</span><b>Mon repas</b><small>Aliments + quantités</small></button><button class="publishChoice session" data-t="session"><span>🏋️‍♀️</span><b>Ma séance</b><small>Exercices + séries</small></button><button class="publishChoice progress" data-t="progress"><span>✨</span><b>Mes progrès</b><small>Photo + comparaison</small></button></div>';document.querySelectorAll('.publishChoice').forEach(b=>b.onclick=()=>form(b.dataset.t))}
function form(t){state.type=t;state.imageData='';title(labels[t],t==='session'?'Sélectionne tes exercices et détaille-les':t==='meal'?'Sélectionne tes aliments et leurs quantités':'Montre ton évolution',true);document.getElementById('publishBody').innerHTML=t==='session'?sessionHtml():t==='meal'?mealHtml():progressHtml();bind(t)}
function searchHtml(id,ph,sug){return `<div class="smartSearch"><input id="${id}" placeholder="${ph}"><div id="${sug}" class="suggestions"></div></div>`}
function photoHtml(){return '<label class="photoDrop"><input id="publishImage" type="file" accept="image/*" capture="environment"><span>＋ Ajouter une photo</span><small>Image compressée automatiquement</small></label><img id="publishPreview" class="publishPreview" alt="Aperçu">'}
function sessionHtml(){return `<div class="publishForm session"><div class="fieldRow"><input id="sessionDuration" placeholder="Temps de séance — ex : 45 min"><input id="sessionRest" placeholder="Temps de repos — ex : 1 min 30"></div>${searchHtml('exerciseSearch','Exercice effectué — écris pour filtrer','exerciseSuggestions')}<div class="exerciseDetailZone"><b>Exercices sélectionnés</b><p>Ajoute un exercice puis indique séries, reps et charge/note.</p><div id="exerciseDetailList" class="exerciseDetailList"></div></div><textarea id="sessionFeeling" placeholder="Ton ressenti — énergie, difficulté, fierté..."></textarea>${photoHtml()}<button class="publishSubmit">Publier ma séance</button><div class="publishStatus"></div></div>`}
function mealHtml(){return `<div class="publishForm meal">${searchHtml('foodSearch','Aliment ou plat — écris pour filtrer','foodSuggestions')}<div class="foodQuantityZone"><b>Aliments sélectionnés</b><p>Ajoute un aliment, puis indique sa quantité juste en dessous.</p><div id="foodQuantityList" class="foodQuantityList"></div></div><textarea id="mealNote" placeholder="Détail du repas — recette, composition, sauce, cuisson..."></textarea>${photoHtml()}<button class="publishSubmit">Publier mon repas</button><div class="publishStatus"></div></div>`}
function progressHtml(){return `<div class="publishForm progress"><textarea id="progressFeeling" placeholder="Ce qui a changé — poids, mensurations, régularité, énergie..."></textarea><label class="compareToggle"><input id="progressCompare" type="checkbox"> <span>Repartager automatiquement mon premier et mon dernier défi</span></label><div id="comparisonPreview">${comparisonHtml()}</div>${photoHtml()}<button class="publishSubmit">Publier mes progrès</button><div class="publishStatus"></div></div>`}
function bind(t){document.getElementById('publishImage').onchange=imgChange;document.querySelector('.publishSubmit').onclick=publish;if(t==='meal')foodSearch();if(t==='session')exerciseSearch();const cb=document.getElementById('progressCompare');if(cb)cb.onchange=()=>{state.progressCompare=cb.checked;document.getElementById('comparisonPreview').classList.toggle('on',cb.checked)}}
function foodSearch(){const input=document.getElementById('foodSearch'),sug=document.getElementById('foodSuggestions'),opts=foods();function draw(){document.getElementById('foodQuantityList').innerHTML=state.foods.length?state.foods.map((f,i)=>`<div class="foodQuantityItem"><div><b>${esc(f.name)}</b><small>Quantité pour cet aliment</small></div><input data-i="${i}" value="${esc(f.quantity)}" placeholder="ex : 150 g, 1 bol"><button data-r="${i}" type="button">×</button></div>`).join(''):'<div class="emptyFoodSelection">Aucun aliment sélectionné pour le moment.</div>';document.querySelectorAll('#foodQuantityList input').forEach(x=>x.oninput=()=>state.foods[+x.dataset.i].quantity=x.value);document.querySelectorAll('#foodQuantityList button').forEach(b=>b.onclick=()=>{state.foods.splice(+b.dataset.r,1);draw();suggest()})}function suggest(){const term=input.value.trim().toLowerCase(),used=state.foods.map(f=>f.name);sug.innerHTML=opts.filter(x=>!used.includes(x)).filter(x=>!term||x.toLowerCase().includes(term)).slice(0,12).map(x=>`<button type="button">${esc(x)}</button>`).join('');sug.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.foods.push({name:b.textContent,quantity:''});input.value='';draw();suggest();input.focus()})}input.oninput=suggest;input.onfocus=suggest;draw();suggest()}
function exerciseSearch(){const input=document.getElementById('exerciseSearch'),sug=document.getElementById('exerciseSuggestions'),opts=exercises();function draw(){document.getElementById('exerciseDetailList').innerHTML=state.exercises.length?state.exercises.map((e,i)=>`<div class="exerciseDetailItem"><div class="exerciseTitle"><b>${esc(e.name)}</b><small>Détails de l’exercice</small></div><input data-f="sets" data-i="${i}" value="${esc(e.sets)}" placeholder="Séries"><input data-f="reps" data-i="${i}" value="${esc(e.reps)}" placeholder="Reps"><input data-f="load" data-i="${i}" value="${esc(e.load)}" placeholder="Charge/note"><button data-r="${i}" type="button">×</button></div>`).join(''):'<div class="emptyExerciseSelection">Aucun exercice sélectionné pour le moment.</div>';document.querySelectorAll('#exerciseDetailList input').forEach(x=>x.oninput=()=>state.exercises[+x.dataset.i][x.dataset.f]=x.value);document.querySelectorAll('#exerciseDetailList button').forEach(b=>b.onclick=()=>{state.exercises.splice(+b.dataset.r,1);draw();suggest()})}function suggest(){const term=input.value.trim().toLowerCase(),used=state.exercises.map(e=>e.name);sug.innerHTML=opts.filter(x=>!used.includes(x)).filter(x=>!term||x.toLowerCase().includes(term)).slice(0,12).map(x=>`<button type="button">${esc(x)}</button>`).join('');sug.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.exercises.push({name:b.textContent,sets:'',reps:'',load:''});input.value='';draw();suggest();input.focus()})}input.oninput=suggest;input.onfocus=suggest;draw();suggest()}
function status(t,k='ok'){const box=document.querySelector('.publishStatus');box.className='publishStatus on '+k;box.textContent=t}
async function imgChange(e){const f=e.target.files?.[0];if(!f)return;try{state.imageData=await compress(f);const p=document.getElementById('publishPreview');p.src=state.imageData;p.classList.add('on');status('Photo ajoutée ✓')}catch{status('Photo trop lourde ou impossible à lire.','err')}}
async function compress(file){const data=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});const img=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=data});const max=420,ratio=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*ratio);c.height=Math.round(img.height*ratio);c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.48)}
function comparison(){const h=history();if(!h.length)return null;return{first:h[h.length-1],last:h[0]}}
function labelChallenge(x){return x?.title||x?.name||x?.challenge||'Défi réalisé'}
function comparisonHtml(){const c=comparison();if(!c)return '<div class="compareBox empty">Aucun défi trouvé pour créer une comparaison.</div>';return `<div class="compareBox"><div><small>Premier défi</small><b>${esc(labelChallenge(c.first))}</b></div><div><small>Dernier défi</small><b>${esc(labelChallenge(c.last))}</b></div></div>`}
async function addSocial(payload){try{return await addDoc(collection(db,'posts'),payload)}catch(e){console.warn('posts bloqué, fallback activity',e);return await addDoc(collection(db,'activity'),{...payload,kind:'socialPost',title:labels[payload.type],emoji:emoji[payload.type],mode:'social',level:payload.type})}}
async function publish(){if(!init())return status('Firebase charge encore. Réessaie.','err');const user=auth.currentUser;if(!user)return status('Connecte-toi pour publier.','err');const type=state.type;let payload={uid:user.uid,name:userName(),type,imageData:state.imageData,likes:[],likesCount:0,createdAt:serverTimestamp()};if(type==='meal'){payload.foodItems=state.foods;payload.foods=state.foods.map(f=>f.quantity?`${f.name} • ${f.quantity}`:f.name);payload.quantity=payload.foods.join(' • ');payload.note=document.getElementById('mealNote')?.value.trim()||'';if(!payload.foodItems.length&&!payload.note&&!payload.imageData)return status('Ajoute au moins un aliment, une note ou une photo.','err')}if(type==='session'){payload.exerciseItems=state.exercises;payload.exercises=state.exercises.map(e=>[e.name,e.sets&&`${e.sets} séries`,e.reps&&`${e.reps} reps`,e.load].filter(Boolean).join(' • '));payload.duration=document.getElementById('sessionDuration')?.value.trim()||'';payload.rest=document.getElementById('sessionRest')?.value.trim()||'';payload.feeling=document.getElementById('sessionFeeling')?.value.trim()||'';if(!payload.exerciseItems.length&&!payload.feeling&&!payload.imageData)return status('Ajoute au moins un exercice, un ressenti ou une photo.','err')}if(type==='progress'){payload.feeling=document.getElementById('progressFeeling')?.value.trim()||'';payload.compare=state.progressCompare?comparison():null;if(!payload.feeling&&!payload.imageData&&!payload.compare)return status('Ajoute une photo, un texte ou la comparaison.','err')}try{document.querySelector('.publishSubmit').disabled=true;await addSocial(payload);window.LARA_SOCIAL_POSTS=[payload,...(window.LARA_SOCIAL_POSTS||[])];status('Publication envoyée ✓');setTimeout(()=>{close();window.openFeed?.()},500)}catch(err){console.warn(err);status('Publication bloquée par Firestore. Mets les règles à jour ou essaie sans photo.','err');document.querySelector('.publishSubmit').disabled=false}}
window.LaraComposer={open,close};
