(()=>{
  const USER_KEY='laraUserV4', HISTORY_KEY='laraHistoryV4', FAVORITES_KEY='laraFavoritesV4', FRIENDS_KEY='laraFriendsV4';
  const LEVELS={debutant:'Débutant',intermediaire:'Intermédiaire',confirme:'Confirmé'};
  const $=id=>document.getElementById(id);
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
  const save=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
  const esc=value=>String(value??'').replace(/[&<>"']/g,letter=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[letter]));
  function currentUser(){return read(USER_KEY,null)||read('laraUser',null)||{name:'Invitée',email:''}}
  function showSafe(id){document.querySelectorAll('.screen').forEach(screen=>screen.classList.remove('on'));const target=$(id);if(target)target.classList.add('on');window.scrollTo({top:0,behavior:'smooth'})}
  function countBy(list,key){return list.reduce((acc,item)=>{const value=item[key]||'Autre';acc[value]=(acc[value]||0)+1;return acc},{})}
  function topKey(object,fallback='—'){const entries=Object.entries(object);return entries.length?entries.sort((a,b)=>b[1]-a[1])[0][0]:fallback}
  function formatDate(value){try{return new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short'}).format(new Date(value))}catch{return '—'}}
  function minutesFrom(time){const text=String(time||''),minutes=(text.match(/(\d+)\s*min/)||[])[1],seconds=(text.match(/(\d+)\s*s/)||[])[1];return (minutes?Number(minutes):0)+(seconds?Number(seconds)/60:0)}
  function statsFrom(history){const mode=countBy(history,'mode');return{total:history.length,week:history.filter(item=>Date.now()-new Date(item.date).getTime()<7*86400000).length,minutes:Math.round(history.reduce((sum,item)=>sum+(Number(item.minutes)||minutesFrom(item.time)),0)),mode:topKey(mode,'—')}}
  function ensureTopButtons(){const top=document.querySelector('.topActions');if(!top)return;let profile=$('profileNav');if(!profile){profile=document.createElement('button');profile.id='profileNav';profile.textContent='Mon profil';top.insertBefore(profile,top.firstChild)}profile.classList.remove('hide');profile.type='button';profile.onclick=event=>{event.preventDefault();openProfileFixed()};let feed=$('feedNav');if(!feed){feed=document.createElement('button');feed.id='feedNav';feed.className='feedNavButton';feed.textContent='Fil';const instagram=top.querySelector('a');top.insertBefore(feed,instagram||null)}feed.classList.remove('hide');feed.type='button';feed.onclick=event=>{event.preventDefault();openFeedFixed()}}
  function applyAvatar(){const avatar=$('avatar'),user=currentUser();if(!avatar)return;const key='laraProfilePhotoV4:'+String(user.name||'invitee').toLowerCase().replace(/\s+/g,'-'),photo=localStorage.getItem(key);if(photo){avatar.style.backgroundImage=`url("${photo}")`;avatar.classList.add('hasPhoto');avatar.textContent=''}else{avatar.style.backgroundImage='';avatar.classList.remove('hasPhoto');avatar.textContent=String(user.name||'L').charAt(0).toUpperCase()}}
  function renderProfileFixed(){const user=currentUser(),history=read(HISTORY_KEY,[]),favs=read(FAVORITES_KEY,[]),stats=statsFrom(history),modeCounts=countBy(history,'mode'),levelCounts=countBy(history,'level'),catCounts=countBy(history,'category');if($('profileName'))$('profileName').textContent=user.name||'Mon profil';if($('profileEmail'))$('profileEmail').textContent=user.email||'Profil enregistré sur ce téléphone';if($('statTotal'))$('statTotal').textContent=stats.total;if($('statWeek'))$('statWeek').textContent=stats.week;if($('statTime'))$('statTime').textContent=stats.minutes;if($('statMode'))$('statMode').textContent=stats.mode==='duo'?'Duo':stats.mode==='solo'?'Solo':'—';if($('profileStats'))$('profileStats').innerHTML=[`Niveau préféré : ${LEVELS[topKey(levelCounts)]||'—'}`,`Catégorie favorite : ${topKey(catCounts)}`,`Solo : ${modeCounts.solo||0}`,`Duo : ${modeCounts.duo||0}`].map(text=>`<span class="chip">${esc(text)}</span>`).join('');if($('preferredCategories')){const topCats=Object.entries(catCounts).sort((a,b)=>b[1]-a[1]).slice(0,4);$('preferredCategories').innerHTML=topCats.length?topCats.map(([name,total])=>`<span class="chip">${esc(name)} • ${total}</span>`).join(''):'<span class="empty">Tes catégories préférées apparaîtront après tes premiers défis.</span>'}if($('favoriteList'))$('favoriteList').innerHTML=favs.length?favs.slice(0,8).map(item=>`<div class="favoriteItem"><div><b>${esc(item.emoji||'✨')} ${esc(item.title)}</b><span>${esc(item.category||'')} • ${esc(LEVELS[item.level]||item.level||'')}</span></div></div>`).join(''):'<div class="empty">Appuie sur le cœur d’un défi pour l’ajouter ici.</div>';if($('recentList'))$('recentList').innerHTML=history.length?history.slice(0,10).map(item=>`<div class="historyItem"><div class="historyMain"><b>${esc(item.emoji||'✨')} ${esc(item.title)}</b><span>${formatDate(item.date)} • ${esc(LEVELS[item.level]||item.level||'')} • ${esc(item.time||'')}</span></div><span class="historyBadge">${item.mode==='duo'?'Duo':'Solo'}</span></div>`).join(''):'<div class="empty">Aucun défi terminé pour le moment.</div>';applyAvatar();ensureFriendPanel()}
  function shortCodePayload(){const user=currentUser(),history=read(HISTORY_KEY,[]),s=statsFrom(history),recent=history.slice(0,5).map(item=>({d:item.date,t:item.title,e:item.emoji,m:item.mode,l:item.level,ti:item.time}));const raw=JSON.stringify({n:user.name,s,r:recent});return 'LDL.'+btoa(unescape(encodeURIComponent(raw))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
  function readShortCode(code){const value=String(code||'').trim();if(value.startsWith('LDL.')){const raw=decodeURIComponent(escape(atob(value.slice(4).replace(/-/g,'+').replace(/_/g,'/')+'==')));const data=JSON.parse(raw);return{id:String(data.n||'amie').toLowerCase().replace(/[^a-z0-9]+/g,'-'),name:data.n||'Amie',generatedAt:new Date().toISOString(),stats:data.s||{},recent:(data.r||[]).map(item=>({date:item.d,title:item.t,emoji:item.e,mode:item.m,level:item.l,time:item.ti}))}}if(typeof decodeFriendData==='function')return decodeFriendData(value);throw Error('code')}
  function ensureFriendPanel(){const card=document.querySelector('#profile .card');if(!card||$('friendsSection')){renderFriendsFixed();return}const box=document.createElement('div');box.className='sectionBox';box.id='friendsSection';box.innerHTML='<h3>Mes amis et comparaison</h3><p class="sub">Copie ton code court et colle celui d’une amie pour comparer vos défis.</p><div class="socialGrid"><button class="btn ghost" id="copyFriendCodeBtn">Copier mon code court</button><button class="btn secondary" id="showFriendCodeBtn">Afficher mon code</button></div><textarea id="myFriendCode" class="friendCodeBox" rows="2" readonly></textarea><div id="copyState" class="copyState"></div><h3>Ajouter une amie</h3><textarea id="friendCodeInput" class="friendCodeBox" rows="2" placeholder="Colle ici le code court reçu"></textarea><button class="btn" id="addFriendBtn">Ajouter cette amie</button><div id="friendsList"></div></div>';const actions=card.querySelector('.profileActions');if(actions)actions.insertAdjacentElement('beforebegin',box);else card.appendChild(box);$('showFriendCodeBtn').onclick=showFriendCode;$('copyFriendCodeBtn').onclick=copyFriendCode;$('addFriendBtn').onclick=addFriendCode;renderFriendsFixed()}
  function showFriendCode(){const code=shortCodePayload();if($('myFriendCode')){$('myFriendCode').value=code;$('myFriendCode').rows=2}if($('copyState'))$('copyState').textContent='Code court : '+code.length+' caractères.';return code}
  async function copyFriendCode(){const code=showFriendCode();try{await navigator.clipboard.writeText(code);$('copyState').textContent='Code copié ✓ • '+code.length+' caractères'}catch{$('myFriendCode')?.select();document.execCommand('copy');$('copyState').textContent='Code copié ✓'}}
  function addFriendCode(){const input=$('friendCodeInput');if(!input||!input.value.trim())return alert('Colle le code ami.');try{const friend=readShortCode(input.value),list=read(FRIENDS_KEY,[]),index=list.findIndex(item=>item.id===friend.id||String(item.name).toLowerCase()===String(friend.name).toLowerCase());if(index>=0)list[index]=friend;else list.unshift(friend);save(FRIENDS_KEY,list);input.value='';renderFriendsFixed();alert(friend.name+' a été ajoutée.')}catch{alert('Code ami invalide.')}}
  function renderFriendsFixed(){const box=$('friendsList');if(!box)return;const list=read(FRIENDS_KEY,[]),my=statsFrom(read(HISTORY_KEY,[]));if(!list.length){box.innerHTML='<div class="emptySocial">Aucune amie ajoutée pour le moment.</div>';return}box.innerHTML=list.map(friend=>{const diff=(my.total||0)-(friend.stats?.total||0);return `<article class="friendItem"><div class="friendHead"><div class="friendIdentity"><div class="friendAvatar">${esc(String(friend.name||'?').charAt(0).toUpperCase())}</div><div class="friendName"><b>${esc(friend.name||'Amie')}</b><span>${esc(friend.stats?.mode==='duo'?'Duo':friend.stats?.mode==='solo'?'Solo':'Mode libre')}</span></div></div></div><div class="friendStats"><div class="friendStat"><b>${friend.stats?.total||0}</b><span>Défis</span></div><div class="friendStat"><b>${friend.stats?.minutes||0}</b><span>Minutes</span></div><div class="friendStat"><b>${friend.stats?.week||0}</b><span>Semaine</span></div></div><div class="comparison">${diff===0?'Vous êtes au même niveau de défis.':diff>0?'Tu as '+diff+' défi(s) de plus.':esc(friend.name)+' a '+Math.abs(diff)+' défi(s) de plus.'}</div></article>`}).join('')}
  function ensureFeedSection(){let feed=$('feed');if(feed)return feed;const main=document.querySelector('main.app');feed=document.createElement('section');feed.id='feed';feed.className='screen';feed.innerHTML='<div class="card"><button class="btn secondary" id="feedBackBtn">← Retour aux défis</button><h2>Fil d’actualité</h2><p class="feedIntro">Tes derniers défis et ceux des amies ajoutées par code.</p><div id="feedList"></div><div class="cloudNotice">Le fil se met à jour avec les codes amis reçus.</div></div>';main.appendChild(feed);$('feedBackBtn').onclick=()=>showSafe('home');return feed}
  function renderFeedFixed(){ensureFeedSection();const own=read(HISTORY_KEY,[]).map(item=>({...item,owner:currentUser().name||'Moi',ownerType:'Moi'})),friends=read(FRIENDS_KEY,[]).flatMap(friend=>(friend.recent||[]).map(item=>({...item,owner:friend.name,ownerType:'Amie'}))),items=own.concat(friends).sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,40);const box=$('feedList');if(!box)return;if(!items.length){box.innerHTML='<div class="emptySocial">Le fil apparaîtra après ton premier défi ou après l’ajout d’une amie.</div>';return}box.innerHTML=items.map(item=>`<article class="feedItem"><div class="feedAvatar">${esc(String(item.owner||'?').charAt(0).toUpperCase())}</div><div class="feedContent"><b>${esc(item.owner||'Participante')}<span class="onlineBadge">${esc(item.ownerType)}</span></b><p>${esc(item.emoji||'✨')} ${esc(item.title||'Défi terminé')}</p><span>${formatDate(item.date)} • ${item.mode==='duo'?'Duo':'Solo'} • ${esc(LEVELS[item.level]||item.level||'')}</span></div></article>`).join('')}
  function openProfileFixed(){renderProfileFixed();showSafe('profile')}
  function openFeedFixed(){renderFeedFixed();showSafe('feed')}
  window.openProfile=openProfileFixed;window.openFeed=openFeedFixed;
  function bindClicks(){ensureTopButtons();document.querySelectorAll('#profileNav,[onclick="openProfile()"],button').forEach(button=>{const label=(button.textContent||'').toLowerCase();if(button.id==='profileNav'||label.includes('profil'))button.onclick=event=>{event.preventDefault();openProfileFixed()};if(button.id==='feedNav'||label.trim()==='fil')button.onclick=event=>{event.preventDefault();openFeedFixed()}})}
  document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;const label=(button.textContent||'').toLowerCase();if(button.id==='profileNav'||label.includes('profil')){event.preventDefault();openProfileFixed()}if(button.id==='feedNav'||label.trim()==='fil'){event.preventDefault();openFeedFixed()}},true);
  document.addEventListener('DOMContentLoaded',bindClicks);
  setTimeout(bindClicks,300);setTimeout(bindClicks,1200);
})();
